### ISSUE TITLE
Compatibility with Laravel v10

### ISSUE THREAD

**Issue by Kreshnik** [gldrenthe89/nova-string-generator-field#10]
As of current the library is not working with Laravel v10

```
 Problem 1
    - Conclusion: don't install gldrenthe89/nova-string-generator-field v3.0.2 (conflict analysis result)
    - optimistdigital/nova-translations-loader 5.0.0
```

**Comment by gldrenthe89** [comment]
Hi. thats true, composer is correctly checking for V9:
 "illuminate/support": "^9.0",

If you want v10 support, you are free to create a pr. I dont have the time at the moment to look into this.
