### ISSUE TITLE
Buttons not translatable, check for readonly property of field.

### ISSUE THREAD

**Issue by ramonfeleus** [gldrenthe89/nova-string-generator-field#2]
Hi,
I've added a pull request #1 to allow the following:

- Translate the text shown on the buttons.
- Check if the field is readonly, if so: hide the Generate button, Only activate Copy button when the field contains a value.

For context: I was using the field for generating unique coupon codes. Once generated and saved it we don't want the field to be updated again. And we have our backend in dutch ;-)

**Comment by ramonfeleus** [comment]
PR already merged, thanks for accepting!

**Comment by gldrenthe89** [comment]
Thanks for the PR. i will create a feature release now.

**Comment by gldrenthe89** [comment]
Released: [v2.1](https://github.com/gldrenthe89/nova-string-generator-field/releases/tag/v2.1)
