### ISSUE TITLE
issue loading translations of other Nova modules

### ISSUE THREAD

**Issue by ramonfeleus** [gldrenthe89/nova-string-generator-field#3]
There's an issue loading translations for other Nova modules. This might be related to the nova-translations-loader plugin I've used for translating the Vue buttons of this package. I've posted an issue there: https://github.com/optimistdigital/nova-translations-loader/issues/6

**Comment by ramonfeleus** [comment]
PR created for fix in optimistdigital/nova-translations-loader library at https://github.com/optimistdigital/nova-translations-loader/pull/7

**Comment by gldrenthe89** [comment]
Lets wait for that PR to be accepted.

**Comment by ramonfeleus** [comment]
The PR has been accepted & merged. So the fix will likely be available in a new release.

**Comment by ramonfeleus** [comment]
Issue fixed in v3.1.2 of optimistdigital/nova-translations-loader, closing issue here.

**Comment by gldrenthe89** [comment]
No need for a new PR then?

**Comment by gldrenthe89** [comment]
> Issue fixed in v3.1.2 of optimistdigital/nova-translations-loader, closing issue here.

No need for a new PR then?

**Comment by ramonfeleus** [comment]
I updated the minimum version in composer.json just in case. But it worked in my project without that too. PR #4

**Comment by gldrenthe89** [comment]
I have merged and released v2.1.1. thanks for the pr
